//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0145ceff_a6bc_463a_a58c_f396688bca5f {
            get {
                object obj = ResourceManager.GetObject("0145ceff-a6bc-463a-a58c-f396688bca5f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0145ceff_a6bc_463a_a58c_f396688bca5f1 {
            get {
                object obj = ResourceManager.GetObject("0145ceff-a6bc-463a-a58c-f396688bca5f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10024145 {
            get {
                object obj = ResourceManager.GetObject("10024145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100241451 {
            get {
                object obj = ResourceManager.GetObject("100241451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _204_2047577_view_refresh_gion_simple_update_button_logo_png_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("204-2047577_view-refresh-gion-simple-update-button-logo-png-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _291fb7c7_8a99_4893_b661_d67b75829fa7 {
            get {
                object obj = ResourceManager.GetObject("291fb7c7-8a99-4893-b661-d67b75829fa7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_116888225_9Wh82kihECBsbau4uCHwdrzO09hXa3zZ {
            get {
                object obj = ResourceManager.GetObject("360_F_116888225_9Wh82kihECBsbau4uCHwdrzO09hXa3zZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_267369938_lUENWU9fJmeTHqqwnNVJpYtfN3pIDR1o {
            get {
                object obj = ResourceManager.GetObject("360_F_267369938_lUENWU9fJmeTHqqwnNVJpYtfN3pIDR1o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_267369938_lUENWU9fJmeTHqqwnNVJpYtfN3pIDR1o1 {
            get {
                object obj = ResourceManager.GetObject("360_F_267369938_lUENWU9fJmeTHqqwnNVJpYtfN3pIDR1o1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3bc54dea_9688_4b37_8574_42184dbfd95b {
            get {
                object obj = ResourceManager.GetObject("3bc54dea-9688-4b37-8574-42184dbfd95b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4K_Batman_Wallpapers_High_Quality_Free_Download {
            get {
                object obj = ResourceManager.GetObject("4K Batman Wallpapers High Quality Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6681204 {
            get {
                object obj = ResourceManager.GetObject("6681204", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6e41dd86_b41a_47c6_8667_6cf87b10563f {
            get {
                object obj = ResourceManager.GetObject("6e41dd86-b41a-47c6-8667-6cf87b10563f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6e41dd86_b41a_47c6_8667_6cf87b10563f1 {
            get {
                object obj = ResourceManager.GetObject("6e41dd86-b41a-47c6-8667-6cf87b10563f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81f00dfb70ffcf40aca178076e813917 {
            get {
                object obj = ResourceManager.GetObject("81f00dfb70ffcf40aca178076e813917", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _86972869_3744_4c27_85b9_2426bdc20d0d {
            get {
                object obj = ResourceManager.GetObject("86972869-3744-4c27-85b9-2426bdc20d0d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_luxury_gradient_blue_background_smooth_dark_blue_with_black_vignette_studio_banner_1258_52393 {
            get {
                object obj = ResourceManager.GetObject("abstract-luxury-gradient-blue-background-smooth-dark-blue-with-black-vignette-stu" +
                        "dio-banner_1258-52393", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bbf5d260_7486_4fb1_b421_f812d99f8df1 {
            get {
                object obj = ResourceManager.GetObject("bbf5d260-7486-4fb1-b421-f812d99f8df1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_contacts_icon {
            get {
                object obj = ResourceManager.GetObject("blue contacts icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_icons {
            get {
                object obj = ResourceManager.GetObject("Blue icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Lock_icon {
            get {
                object obj = ResourceManager.GetObject("Blue Lock icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c890338f_b34a_4594_8028_2ae9a916cff1 {
            get {
                object obj = ResourceManager.GetObject("c890338f-b34a-4594-8028-2ae9a916cff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c90e9f73_cfa2_4675_80be_0b88d6a9f8db {
            get {
                object obj = ResourceManager.GetObject("c90e9f73-cfa2-4675-80be-0b88d6a9f8db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cf15bb87_7db7_4b1b_b513_ddb731dceec6 {
            get {
                object obj = ResourceManager.GetObject("cf15bb87-7db7-4b1b-b513-ddb731dceec6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap components_buttons_usage1_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("components-buttons-usage1-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap components_buttons_usage1_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("components-buttons-usage1-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_ {
            get {
                object obj = ResourceManager.GetObject("download (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fbd1e91a_871a_41b5_a73f_1c21e281f915 {
            get {
                object obj = ResourceManager.GetObject("fbd1e91a-871a-41b5-a73f-1c21e281f915", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit_form_young_athletes_push_up_technique_black_vector_icon_power_push_sporty_males_push_up_persist_974322_26319 {
            get {
                object obj = ResourceManager.GetObject("fit-form-young-athletes-push-up-technique-black-vector-icon-power-push-sporty-mal" +
                        "es-push-up-persist_974322-26319", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_search_icon_2911_thumb {
            get {
                object obj = ResourceManager.GetObject("free-search-icon-2911-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20220226_1450_14qeapr_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("image_processing20220226-1450-14qeapr-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap judo_athlete_icon_trendy_flat_style_isolated_1323048_55721_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("judo-athlete-icon-trendy-flat-style-isolated_1323048-55721-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap judo_athlete_icon_trendy_flat_style_isolated_1323048_55721_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("judo-athlete-icon-trendy-flat-style-isolated_1323048-55721-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap judo_illustration_KHY0KD_magic {
            get {
                object obj = ResourceManager.GetObject("judo-illustration-KHY0KD_magic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap judo_illustration_KHY0KD_magic1 {
            get {
                object obj = ResourceManager.GetObject("judo-illustration-KHY0KD_magic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kick_last__3__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kick_last__3_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_menu_icons_content_view_260nw_2589536751_gigapixel_standard_v2_2x {
            get {
                object obj = ResourceManager.GetObject("list-menu-icons-content-view-260nw-2589536751-gigapixel-standard v2-2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login__button_vectors__sign_label_speech_login_Photoroom {
            get {
                object obj = ResourceManager.GetObject("login  button vectors_ sign label speech login-Photoroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login__button_vectors__sign_label_speech_login_Photoroom_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("login__button_vectors__sign_label_speech_login-Photoroom-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login__button_vectors__sign_label_speech_login_Photoroom_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("login__button_vectors__sign_label_speech_login-Photoroom-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login__button_vectors__sign_label_speech_login_Photoroom_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("login__button_vectors__sign_label_speech_login-Photoroom-removebg-preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password_icon_1903x2048_m0d1f305 {
            get {
                object obj = ResourceManager.GetObject("password-icon-1903x2048-m0d1f305", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_android_web_search_engine_google_search_search_box_google_search_bar_blue_trademark_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-android-web-search-engine-google-search-search-box-goo" +
                        "gle-search-bar-blue-trademark-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_back_icon_png_image_1023353 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-back-icon-png-image_1023353", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Бесплатные__звезда__погода__солнце_фон_картинки__небо_свет_пространство_лед_справочная_информация_Фото_Фон_PNG_и_векторы {
            get {
                object obj = ResourceManager.GetObject("Бесплатные  звезда, погода, солнце фон картинки, небо свет пространство лед справ" +
                        "очная информация Фото Фон PNG и векторы", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
